package com.singtempo.offlinecontactpayment;

import android.app.*;import android.content.*;import android.net.*;import android.os.*;import android.provider.MediaStore;import android.util.Base64;import android.webkit.*;import java.io.*;

public class MainActivity extends Activity {
 private WebView webView; private ValueCallback<Uri[]> fileCallback; private static final int FILE_CHOOSER=1001;
 @Override public void onCreate(Bundle b){super.onCreate(b); webView=new WebView(this);setContentView(webView);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);
  webView.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return handle(r.getUrl());}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return handle(Uri.parse(u));}boolean handle(Uri u){if("tel".equalsIgnoreCase(u.getScheme())){startActivity(new Intent(Intent.ACTION_DIAL,u));return true;}return false;}});
  webView.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;Intent i=p.createIntent();i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");try{startActivityForResult(i,FILE_CHOOSER);}catch(Exception e){fileCallback=null;cb.onReceiveValue(null);}return true;}});
  webView.addJavascriptInterface(new AndroidBridge(),"AndroidBridge");webView.loadUrl("file:///android_asset/index.html");
 }
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==FILE_CHOOSER&&fileCallback!=null){Uri[] x=null;if(c==RESULT_OK&&d!=null&&d.getData()!=null)x=new Uri[]{d.getData()};fileCallback.onReceiveValue(x);fileCallback=null;}}
 public class AndroidBridge{@JavascriptInterface public void saveExcel(String base64,String filename){try{byte[] bytes=Base64.decode(base64,Base64.DEFAULT);if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,filename);v.put(MediaStore.Downloads.MIME_TYPE,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS);v.put(MediaStore.Downloads.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception("Could not create Downloads file");try(OutputStream o=getContentResolver().openOutputStream(u)){if(o==null)throw new Exception("Could not open Downloads file");o.write(bytes);}ContentValues done=new ContentValues();done.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(u,done,null,null);}else{File dir=Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);if(!dir.exists()&&!dir.mkdirs())throw new Exception("Could not create Downloads directory");try(OutputStream o=new FileOutputStream(new File(dir,filename))){o.write(bytes);}}runOnUiThread(()->Toast.makeText(MainActivity.this,"Excel saved to Downloads",Toast.LENGTH_LONG).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"Export failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}}
 @Override public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
}
